### PR TITLE
Add support for ClimateEntityFeature.TURN_ON

### PR DESCRIPTION
**Pull request by MoFtZ**
Depends on #33 to be merged first.

### CODE REVIEW

**Comment by boc-the-git** [comment]
@MoFtZ on #33 you said
> I'm assuming we can send the system "on" command by itself, but have not tried.
This should be the same as pressing the "on" button on the remotes - where the Bonaire unit will remember its last settings.

In your testing, is that the exact function of the command, the same as pressing the power button on the remote?

**Comment by MoFtZ** [comment]
> In your testing, is that the exact function of the command, the same as pressing the power button on the remote?

Yes, that is the behaviour that I observed. The unit retains its previous settings.

**Comment by boc-the-git** [comment]
Nice one! I'll give it a quick test tomorrow (hopefully), then push out a release

**Comment by boc-the-git** [comment]
@MoFtZ I'm unable to get the turn on functionality to work.. is there anything you had to do to get it working in HA?

image

I have tried everything I can think of short of removing and adding the entity again. I was hoping that's not a necessity, but maybe it is?

**Comment by MoFtZ** [comment]
I did not use the GUI inside HA.

My setup is run via HomeKit Bridge, and I tested it using the Climate Turn On Automation.

How is that GUI configured?

**Comment by boc-the-git** [comment]
My entity has this state, before I delete it:
```
hvac_modes:
  - "off"
  - fan_only
  - heat
  - cool
min_temp: 10
max_temp: 32
target_temp_step: 1
fan_modes:
  - econ
  - thermo
  - boost
preset_modes:
  - Common
current_temperature: 21
temperature: 18
fan_mode: thermo
preset_mode: Common
friendly_name: Bonaire MyClimate
supported_features: 409
```

Deleting it and recreating doesn't really do anything.. I think it isn't fully deleted or something and the entity still exists in some form.
That said, I've had the code in my system for ~24 hours now and I don't see any _negative_ provided by this.

Thanks for the PR @MoFtZ

**Comment by boc-the-git** [comment]
That GUI is nothing special, it's the standard HA climate entity, in 2024.7

**Pull request merged**
